# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDeck < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/qzchenwl/agent-deck"
  version "0.26.0-cwl.2"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.0-cwl.2/agent-deck_0.26.0-cwl.2_darwin_amd64.tar.gz"
      sha256 "02bed583fa56b5a7d9df38083c85987a0c4f73775b86d8b8482be089ec5e6498"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.0-cwl.2/agent-deck_0.26.0-cwl.2_darwin_arm64.tar.gz"
      sha256 "e072f08ec78500bb6502c87d20854c4217069d1a64bf5ae3c0a046657dc2446f"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.0-cwl.2/agent-deck_0.26.0-cwl.2_linux_amd64.tar.gz"
      sha256 "d0b776d755114dc4b72f93bb05776134e6225b47e8b034981eac83b3014df2e8"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.0-cwl.2/agent-deck_0.26.0-cwl.2_linux_arm64.tar.gz"
      sha256 "2a1475cb0acdc8d6de97569eecf118a9b8b53300be7d9d43ff79cd25544ac802"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  test do
    system "#{bin}/agent-deck", "version"
  end
end
