# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentDeck < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/qzchenwl/agent-deck"
  version "0.26.4-cwl.4"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.4-cwl.4/agent-deck_0.26.4-cwl.4_darwin_amd64.tar.gz"
      sha256 "046f8076837cca3603df5a5bf0b8c4665ff5864d43c1ecb5c461b8631e10d2c9"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.4-cwl.4/agent-deck_0.26.4-cwl.4_darwin_arm64.tar.gz"
      sha256 "3c6789fa3407a3977832042e96d4fd41b5a65884952f92c0c34f499d76255848"

      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.4-cwl.4/agent-deck_0.26.4-cwl.4_linux_amd64.tar.gz"
      sha256 "7b9b627b198c06a3197f05b11ee7267f5cb02866b6af011e5479ec38b5c48eec"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qzchenwl/agent-deck/releases/download/v0.26.4-cwl.4/agent-deck_0.26.4-cwl.4_linux_arm64.tar.gz"
      sha256 "371ca60675ee1ad3a566f8b635eee17c5e388bfc882e004cb66938ec9a5935e2"
      define_method(:install) do
        bin.install "agent-deck"
      end
    end
  end

  test do
    system "#{bin}/agent-deck", "version"
  end
end
